### ISSUE TITLE
Comunicação do front com o back

### ISSUE THREAD

**Issue by Diegoslourenco** [leovdn/squad3-fifo#17]
Implementar comunicação do front com o back

**Comment by leovdn** [comment]
Realizado teste de conexão com backend e bando de dados.
Conexão de testes realizada no NodeJS onde os dados são fornecidos pela API, com liberação de acesso pelo CORS. Do lado Frontend foi realizada chamada assíncrona utilizando o Fetch API. 

![Fcamara](https://user-images.githubusercontent.com/21160525/98871972-8f99b480-2454-11eb-83c7-4ffaa1f846ed.gif)
